"""
AutoValue AI — Flask web app
Integrates: car price estimation, depreciation analysis, Claude AI recommendations
"""

import os
import json
from typing import Optional
import pandas as pd
import numpy as np
from flask import Flask, jsonify, request, render_template
import sys, os
from dotenv import load_dotenv
load_dotenv()
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))
from modeling_components.car_depreciation_estimator import CarDepreciationEstimator
from modeling_components.car_recommender import CarRecommender

app = Flask(__name__)

# ---------------------------------------------------------------------------
# Load dataset once at startup
# ---------------------------------------------------------------------------
DATA_PATH = "data/modeling_data/mexico_cars_complete.csv"
df = pd.DataFrame()
estimator = None
MAKES = []
MODELS_BY_MAKE = {}
YEARS = []

def _load_data():
    global df, estimator, MAKES, MODELS_BY_MAKE, YEARS
    try:
        df = pd.read_csv(DATA_PATH)
        # Ensure car_age exists
        if 'car_age' not in df.columns:
            df['car_age'] = 2026 - df['year']
        df = df.dropna(subset=['price', 'year', 'make', 'model'])
        df['price'] = pd.to_numeric(df['price'], errors='coerce')
        df['miles'] = pd.to_numeric(df['miles'], errors='coerce').fillna(0)
        df = df[df['price'] > 0]

        estimator = CarDepreciationEstimator(df)
        estimator.calculate_brand_depreciation()   # pre-compute brand rates

        MAKES = sorted(df['make'].dropna().unique().tolist())
        MODELS_BY_MAKE = {
            make: sorted(df[df['make'] == make]['model'].dropna().unique().tolist())
            for make in MAKES
        }
        YEARS = sorted(df['year'].dropna().astype(int).unique().tolist(), reverse=True)
        print(f"Loaded {len(df)} cars | {len(MAKES)} makes")
    except Exception as e:
        print(f"Warning: could not load data — {e}")

_load_data()

# ---------------------------------------------------------------------------
# Retail price lookup — loaded from data/car_retail_prices.csv
# Generated by generate_retail_prices.py (brand/year/body formula + 0-mile inventory)
# ---------------------------------------------------------------------------
RETAIL_CSV = "data/modeling_data/car_retail_prices.csv"
retail_df: pd.DataFrame = pd.DataFrame()

def _load_retail_prices():
    global retail_df
    try:
        retail_df = pd.read_csv(RETAIL_CSV)
        print(f"Retail prices loaded: {len(retail_df)} entries")
    except FileNotFoundError:
        print(f"Warning: {RETAIL_CSV} not found — run generate_retail_prices.py first")

_load_retail_prices()


def get_retail_price(make: str, model: str, year: int) -> "Optional[float]":
    """
    Return the estimated retail (MSRP) price in MXN for a make/model/year.

    Match priority:
      1. Exact make + model + year (any body type → median)
      2. Same make + model, nearest year
      3. Same make, apply brand-average depreciation from nearest year
    """
    if retail_df.empty:
        return None

    year = int(year)

    # 1. Exact match (may have multiple body types — take median)
    exact = retail_df[(retail_df['make'] == make) &
                      (retail_df['model'] == model) &
                      (retail_df['year'] == year)]
    if not exact.empty:
        return float(exact['retail_price_mxn'].median())

    # 2. Same make/model, closest year
    model_rows = retail_df[(retail_df['make'] == make) & (retail_df['model'] == model)]
    if not model_rows.empty:
        closest_yr = model_rows.iloc[(model_rows['year'] - year).abs().argsort()[:1]]['year'].values[0]
        ref_price  = float(model_rows[model_rows['year'] == closest_yr]['retail_price_mxn'].median())
        yr_diff    = int(closest_yr) - year
        brand_rate = estimator.brand_rates.get(make)
        ind_rates  = estimator.get_industry_standard_rates()
        price = ref_price
        for _ in range(abs(yr_diff)):
            rate = (brand_rate / 100) if brand_rate else (ind_rates.get(5, 8.0) / 100)
            # adjust toward requested year
            price = price * (1 - rate) if yr_diff > 0 else price / max(1 - rate, 0.01)
        return round(price, 0)

    # 3. Same make only — return median for closest year
    make_rows = retail_df[retail_df['make'] == make]
    if not make_rows.empty:
        return float(make_rows['retail_price_mxn'].median())

    return None


# ---------------------------------------------------------------------------
# estimate value from dataset statistics
# ---------------------------------------------------------------------------

def estimate_value(make, model, year, miles, condition="Good", fuel_type=None):
    """Return (estimated_price, confidence_pct, sample_size) from similar listings."""
    if df.empty:
        return None, 0, 0

    year = int(year)
    miles = float(miles)

    # Progressive filtering: exact → ±2yr → same make
    filters = [
        df[(df['make'] == make) & (df['model'] == model) & (df['year'] == year)],
        df[(df['make'] == make) & (df['model'] == model) & (df['year'].between(year - 2, year + 2))],
        df[(df['make'] == make) & (df['model'] == model)],
        df[df['make'] == make],
    ]
    subset = pd.DataFrame()
    for f in filters:
        if len(f) >= 3:
            subset = f
            break
    if subset.empty:
        subset = df

    # Mileage adjustment: ±$4,711 per 10,000 miles vs subset median
    median_miles = subset['miles'].median()
    mileage_adj = -((miles - median_miles) / 10_000) * 4_711

    # Age adjustment using industry depreciation rates from estimator
    industry_rates = estimator.get_industry_standard_rates()
    car_age = 2026 - year
    median_year = int(round(subset['year'].median()))
    base_age = 2026 - median_year
    base_price = subset['price'].median()

    age_adj = 0.0
    if car_age < base_age:
        for a in range(car_age + 1, base_age + 1):
            rate = industry_rates.get(min(a, 10), 2.0) / 100
            age_adj += base_price * rate
    elif car_age > base_age:
        val = base_price
        for a in range(base_age + 1, car_age + 1):
            rate = industry_rates.get(min(a, 10), 2.0) / 100
            val -= val * rate
        age_adj = val - base_price

    # Condition multiplier
    condition_mult = {"Excellent": 1.08, "Good": 1.0, "Fair": 0.90, "Poor": 0.78}.get(condition, 1.0)

    estimated = max((base_price + mileage_adj + age_adj) * condition_mult, 10_000)

    # Confidence based on sample size
    n = len(subset)
    confidence = min(50 + n * 2, 97)

    return round(estimated, 0), confidence, n


def get_depreciation_timeline(make, model, year, estimated_price):
    """Return year-by-year value, best-time-to-sell rows, and sell recommendation."""
    current_age = 2026 - int(year)

    # ── Retail price is only used as display reference in the banner ─────────
    retail = get_retail_price(make, model, year)
    reference_price = retail if retail else estimated_price

    # ── Depreciation projection starts from the estimated current value ───────
    sell_result = estimator.get_best_time_to_sell(
        initial_price=estimated_price,
        make=make,
        model=model,
        current_age=current_age,
        threshold_pct=60.0,
        years_ahead=30,
    )
    projection = sell_result['projection']  # reuse the projection already computed

    # ── Chart data: historical medians (past) + projected future values ──────
    chart = []
    past_data = (
        df[(df['make'] == make) & (df['model'] == model)]
        .groupby('year')['price']
        .median()
        .to_dict()
    )
    for y in sorted(past_data.keys()):
        chart.append({"year": int(y), "value": round(past_data[y], 0), "type": "historical"})

    # projection has 'future_year' = 2026 + (car_age - current_age)
    for _, row in projection.iterrows():
        future_yr = int(row['future_year'])
        if future_yr > 2026:          # only add genuinely future years to chart
            chart.append({"year": future_yr, "value": round(row['projected_value'], 0), "type": "projected"})

    # ── Best-time-to-sell table rows (next 7 projected years) ───────────────
    best_sell = []
    prev_val  = estimated_price
    best_year = sell_result['best_sell_year']

    for _, row in projection.iterrows():
        future_yr = int(row['future_year'])
        if future_yr < 2026:
            continue                  # skip rows before now
        val       = round(row['projected_value'], 0)
        retention = round((val / estimated_price) * 100, 1)
        annual_loss = round(prev_val - val, 0) if future_yr > 2026 else 0
        best_sell.append({
            "year":        future_yr,
            "value":       val,
            "retention":   retention,
            "annual_loss": annual_loss,
            "is_best":     future_yr == best_year,
        })
        prev_val = val
        if len(best_sell) >= 7:
            break

    # ── Summary metrics ──────────────────────────────────────────────────────
    last_val = best_sell[-1]['value'] if best_sell else estimated_price
    total_depr_pct = round((1 - last_val / estimated_price) * 100, 1)
    avg_annual_loss = round((estimated_price - last_val) / len(best_sell), 0) if best_sell else 0

    # ── Recalculate sell recommendation relative to RETAIL price ─────────────
    # retention_pct = how much of the retail price the car still holds at sell year
    value_at_sell = sell_result['value_at_sell']
    retention_vs_retail = round((value_at_sell / reference_price) * 100, 2)

    # crosses_below_year: first year projected value drops below 60% of retail price
    retail_threshold = reference_price * 0.60
    crosses_below_year = None
    for _, row in projection.iterrows():
        if int(row['future_year']) >= 2026 and row['projected_value'] < retail_threshold:
            crosses_below_year = int(row['future_year'])
            break

    # best_sell_year: last year value is still >= 60% of retail price
    best_sell_year_retail = (crosses_below_year - 1) if crosses_below_year else sell_result['best_sell_year']
    years_from_now_retail = max(0, best_sell_year_retail - 2026)

    return {
        "chart": chart,
        "best_sell": best_sell,
        "total_depreciation_pct": total_depr_pct,
        "avg_annual_loss": avg_annual_loss,
        "retail_price": retail,
        "retail_source": "zero_mile_inventory" if (not retail_df.empty and not retail_df[(retail_df['make']==make)&(retail_df['model']==model)&(retail_df['year']==int(year))&(retail_df['source']=='zero_mile_inventory')].empty) else "formula_estimate",
        "sell_recommendation": {
            "best_sell_year":     best_sell_year_retail,
            "best_sell_age":      sell_result['best_sell_age'],
            "years_from_now":     years_from_now_retail,
            "value_at_sell":      value_at_sell,
            "retention_pct":      retention_vs_retail,
            "crosses_below_year": crosses_below_year,
            "threshold_pct":      60.0,
            "reference_price":    reference_price,
        },
    }


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/")
def index():
    return render_template("index.html", makes=MAKES, years=YEARS)


@app.route("/api/models/<make>")
def get_models(make):
    return jsonify(MODELS_BY_MAKE.get(make, []))


@app.route("/api/predict", methods=["POST"])
def predict():
    data = request.get_json()
    make = data.get("make", "")
    model = data.get("model", "")
    year = data.get("year", 2020)
    miles = data.get("miles", 50000)
    condition = data.get("condition", "Good")
    fuel_type = data.get("fuel_type", "")

    if not make or not model:
        return jsonify({"error": "make and model are required"}), 400

    estimated, confidence, sample_n = estimate_value(make, model, year, miles, condition, fuel_type)
    if estimated is None:
        return jsonify({"error": "Could not estimate value — no data available"}), 400

    depr = get_depreciation_timeline(make, model, year, estimated)

    return jsonify({
        "estimated_value": estimated,
        "value_range": [round(estimated * 0.93, 0), round(estimated * 1.07, 0)],
        "confidence": confidence,
        "sample_size": sample_n,
        "total_depreciation_pct": depr["total_depreciation_pct"],
        "avg_annual_loss": depr["avg_annual_loss"],
        "chart": depr["chart"],
        "best_sell": depr["best_sell"],
        "sell_recommendation": depr["sell_recommendation"],
    })


@app.route("/api/recommend", methods=["POST"])
def recommend():
    data = request.get_json()
    text = data.get("text", "").strip()
    if not text:
        return jsonify({"error": "Please describe what you need"}), 400

    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        return jsonify({"error": "ANTHROPIC_API_KEY not configured on server"}), 500

    try:
        rec = CarRecommender(api_key=api_key)
        result = rec.recommend_from_natural_language(text, max_recommendations=3)
        return jsonify(result)
    except Exception as e:
        return jsonify({"error": str(e)}), 500


if __name__ == "__main__":
    app.run(debug=True, port=5050)
